image: Visual Studio 2019

init:
    - git config --global core.autocrlf input

platform:
    - x86

configuration:
    - Debug

matrix:
    fast_finish: false

# install:
    #- cd C:\Tools\vcpkg
    #- git pull
    #- .\bootstrap-vcpkg.bat
    #- vcpkg list
    #- vcpkg install boost
    #- vcpkg integrate install

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - cmake -DUSE_CUSTOM_BOOST_PATH:BOOL=ON -DCUSTOM_BOOST_PATH=C:\Libraries\boost_1_73_0 -G "Visual Studio 16 2019" -T host=x86 -A win32 CMakeLists.txt
    - cmake --build .

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure

after_build:
    - mkdir dist\modules
    - cp BuildingMod\%CONFIGURATION%\building_amxx.dll dist\modules\building_amxx.dll
    - 7z a ${APPVEYOR_PROJECT_NAME}-${APPVEYOR_REPO_TAG_NAME}-win.zip dist

artifacts:
    - path: ${APPVEYOR_PROJECT_NAME}-${APPVEYOR_REPO_TAG_NAME}-win.zip
      name: building_amxx

deploy:
  - provider: GitHub
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: E8RPa4jiZzegokFlfCgIiCdXuXVB5o+TjYaB//eIfKrvP9IbeJ7f7Xl9F6Y+Ld8w
    force_update: true
    artifact: building_amxx
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true