image: Visual Studio 2019

init:
    - git config --global core.autocrlf input

platform:
    - x86

configuration:
    - Debug

matrix:
    fast_finish: false

# install:
    #- cd C:\Tools\vcpkg
    #- git pull
    #- .\bootstrap-vcpkg.bat
    #- vcpkg list
    #- vcpkg install boost
    #- vcpkg integrate install

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - cmake -DUSE_CUSTOM_BOOST_PATH:BOOL=ON -DCUSTOM_BOOST_PATH=C:\Libraries\boost_1_73_0 -G "Visual Studio 16 2019" -T host=x86 -A win32 CMakeLists.txt
    - cmake --build .

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure

after_build:
    - cp --help
    - cp %CONFIGURATION%\building_amxx.dll dist\modules\building_amxx.dll
    - 7z a building_amxx-win-x86.zip dist

artifacts:
    - path: building_amxx-win-x86.zip
      name: building_amxx

deploy:
    provider: GitHub
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
        secure: <secret-github-token>
    force_update: true
    on:
        appveyor_repo_tag: true