# Programming languages
language: cpp

# OS env
dist: trusty

# Compiler
compiler: gcc`

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5-multilib
      - g++-5-multilib
      - cmake
      - linux-libc-dev:i386

script:
  - export CC=gcc-5
  - export CXX=g++-5
  - cmake --version
  - cmake CMakeLists.txt
  - cmake --build . --target building_amxx

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - BuildingMod/building_amxx.so 
  skip_cleanup: true
  on:
    tags: true
    branch: master