# Programming languages
language: cpp

# OS env
dist: trusty
sudo: required

# Compiler
compiler: gcc`

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5-multilib
      - g++-5-multilib
      - cmake
      - linux-libc-dev:i386

script:
  - export CC=gcc-5
  - export CXX=g++-5
  - cmake --version
  - cmake CMakeLists.txt
  - cmake --build . --target building_amxx

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "YOUR GIT USER NAME"
  - git config --local user.email "YOUR GIT USER EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true