image: Visual Studio 2019

init:
    - git config --global core.autocrlf input

platform:
    - x86

configuration:
    - Debug

matrix:
    fast_finish: false

# install:
    #- cd C:\Tools\vcpkg
    #- git pull
    #- .\bootstrap-vcpkg.bat
    #- vcpkg list
    #- vcpkg install boost
    #- vcpkg integrate install

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - cmake -G "Visual Studio 16 2019" -T host=x86 -A win32 CMakeLists.txt -Wno-dev
    - cmake --build .

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure

after_build:
    - mkdir assets\addons\amxmodx\modules
    - cp BuildingMod\%CONFIGURATION%\building_amxx.dll assets\addons\amxmodx\modules\building_amxx.dll
    - set ARCHIVE_NAME=%APPVEYOR_PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-win.zip
    - 7z a %ARCHIVE_NAME% assets

artifacts:
    - path: '*.zip'
      name: building_amxx

deploy:
  - provider: GitHub
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: E8RPa4jiZzegokFlfCgIiCdXuXVB5o+TjYaB//eIfKrvP9IbeJ7f7Xl9F6Y+Ld8w
    force_update: true
    artifact: building_amxx
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true